pub const VERSION : i32 = 1;

pub const ERROR_RESPONSE_OK: &str = "OK";
pub const ERROR_RESPONSE_DOESNT_EXISTS: &str = "DOESNT_EXISTS";
pub const ERROR_RESPONSE_ACCESS_ERROR: &str = "ACCESS_ERROR";
pub const ERROR_RESPONSE_ALREADY_EXISTS: &str = "ALREADY_EXISTS";
pub const ERROR_RESPONSE_INVALID_JSON: &str = "INVALID_JSON";